### ISSUE TITLE
[theyalow] [style.css]

### ISSUE THREAD

**Issue by mascazo** [casss1dy/theyalow#1]
Между правилами стилей лучше оставлять пустую строчку, так повышается читабельность кода. 
Было: 
```
body {
  font: 300 14px/1.3 'Open Sans', sans-serif;
  color: #000;
}
* {
  box-sizing: border-box;
}
```
Хорошо бы:
```
body {
  font: 300 14px/1.3 'Open Sans', sans-serif;
  color: #000;
}

* {
  box-sizing: border-box;
}
```

**Comment by casss1dy** [comment]
писала стили в less, после компиляции в css пустые строки удаляются, убрала .less из гит игнор
