### ISSUE TITLE
[theyalow] [index.html] [row 56-70]

### ISSUE THREAD

**Issue by mascazo** [casss1dy/theyalow#10]
Для чего тут `<div class="line"></div>`, если он не отображается в потоке?

HTML: 
```
<div class="ico-block">
    <div class="line"></div>
    <div class="line"></div>
     ...
</div>
```
CSS: 
```
main .ico-block .line {
  display: none;
}
```

**Comment by casss1dy** [comment]
это промежуточное решение, видимо, какое-то было) убрала из индекса и из стилей
