### ISSUE TITLE
[theyalow] [index.html]

### ISSUE THREAD

**Issue by mascazo** [casss1dy/theyalow#4]
Тегам `<head>` и `<body>` лучше задать отступ, так как они являются вложенными в тег `<html>`
```
<html lang="en">
<head>
     ...
</head>
<body>
    ...
</body>
</html>
```

То же самое касается тегов, вложенных в `<body>`: `<header>`, `<main>` и `<footer>`.

**Comment by casss1dy** [comment]
согласна, однако reformat code в php storm почему-то так правит) поправила руками
