### ISSUE TITLE
[theyalow] [index.html] [row 83-87, 108-112]

### ISSUE THREAD

**Issue by mascazo** [casss1dy/theyalow#6]
1. Идентификатор должен быть уникальным на странице, не допускается повторное использование в других элементах
2. В наименовании идентификатора не допустимо присутствие пробелов

> id задает стилевой идентификатор — уникальное имя элемента, которое используется для изменения его стиля и обращения к нему через скрипты. Идентификатор в коде документа должен быть в единственном экземпляре, иными словами, встречаться только один раз.

> Идентификатор должен обязательно начинаться с латинского символа и может содержать в себе латинские буквы (A–Z, a–z), цифры (0–9), символ дефиса (-) и подчеркивания (_). Использование русских букв в именах идентификатора недопустимо.

```
<g id="section_1">
    <g id="scroll_1">
        <path id="Shape 11" class="shp0" d="M12 8L8 8L8 12L5 12L5 8L1 8L1 5L5 5L5 1L8 1L8 5L12 5L12 8Z" />
    </g>
</g>
```

**Comment by casss1dy** [comment]
копипаста кода из svg, не обратила внимание, убрала в 2 местах
